name:  Wpf Continuous Integration

# Trigger on push and pull_request
on: [push, pull_request]

jobs:

  build:

    strategy:
      matrix:
        configuration: Release
        targetplatform: [x86, x64]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    # Add MsBuild to the PATH. This is not an official Microsoft action:  https://github.com/topics/msbuild-action
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    # Build the solution and create the Msix
    - name: Build MyWpfApp.sln
      run: msbuild MyWpfApp.sln /restore /p:Platform=$env:TargetPlatform /p:Configuration=$env:Configuration /p:UapAppxPackageBuildMode=$env:BuildMode /p:PackageCertificatePassword=$env:PackageCertificatePassword
      env:  
        BuildMode: SideLoadOnly
        Configuration: ${{ matrix.configuration }}
        MsixPath: MyWpfApp.Package\AppPackages\
        PackageCertificatePassword: ${{secrets.Pfx_Key}}
        TargetPlatform: ${{ matrix.targetplatform }}

    # Upload the Msix package: https://github.com/marketplace/actions/upload-artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@master
      with:
        name: Msix Package
        path: MyWpfApp.Package\AppPackages\