name:  Wpf Continuous Integration

# Trigger on push
on: [push]

jobs:

  build:

    strategy:
      matrix:
        targetplatform: [x86, x64]

    runs-on: windows-latest

    env:
      SigningCertificate: EdwardSkrodDeveloper.pfx
      Solution_Path: MyWpfApp.sln
      Test_Project_Path: MyWpfApp.Tests\MyWpfApp.Tests.csproj
      Wpf_Project_Path: MyWpfApp\MyWpfApp.csproj
      Wap_Project_Directory: MyWpfApp.Package
      Wap_Project_Name: MyWpfApp.Package.wapproj

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100

    # Add  MsBuild to the PATH
    - name: Add MSBuild.exe to the system PATH
      run: |
        Install-Module -Name VSSetup -Scope CurrentUser -Force
        $instance = Get-VSSetupInstance -All -Prerelease | Select-VSSetupInstance -Require 'Microsoft.Component.MSBuild' -Latest
        $msbuildPath = Join-Path -Path $instance.InstallationPath -ChildPath "MSBuild\Current\Bin\"
        [Environment]::SetEnvironmentVariable("Path", [Environment]::GetEnvironmentVariable("Path", [EnvironmentVariableTarget]::Machine) + ";$msbuildPath", [EnvironmentVariableTarget]::Machine)

    # Test
    - name: Execute Unit Tests
      run: dotnet test $env:Test_Project_Path

    # Clean the solution to prevent error NETSDK1047
    - name: Clean the solution
      run: msbuild $env:Solution_Path /t:Clean

    # Build the Wpf Net Core application
    - name: Build the Wpf App
      run: msbuild $env:Wpf_Project_Path /restore /p:RuntimeIdentifier=$env:RuntimeIdentifier /p:Platform=$env:TargetPlatform /p:Configuration=$env:Configuration
      env:
        Configuration: Release
        RuntimeIdentifier: win-${{ matrix.targetplatform }}
        TargetPlatform: ${{ matrix.targetplatform }}
        
    # Decode the Base64 encoded Pfx
    - name: Decode the encoded Pfx
      run: Get-Content ${{ secrets.Base64_Encoded_Pfx }} -Encoding UTF8 | Out-File $env:Wap_Project_Directory/$env:SigningCertificate

    # Build the Windows Application Packaging project
    - name: Build the Wap 
      run: msbuild $env:Wap_Project_Directory/$env:Wap_Project_Name /p:Platform=$env:TargetPlatform /p:Configuration=$env:Configuration /p:UapAppxPackageBuildMode=$env:BuildMode /p:AppInstallerUri=$env:AppInstallerUri /p:PackageCertificateKeyFile=$env:Wap_Project_Directory/$env:SigningCertificate /p:PackageCertificatePassword=${{ secrets.Pfx_Key }}
      env:  
        BuildMode: SideLoadOnly
        Configuration: Release
        TargetPlatform: ${{ matrix.targetplatform }}

    # Remove the .pfx
    - name: Remove the .pfx
      run: Remove-Item -path $env:Wap_Project_Directory/$env:SigningCertificate

    # Upload the MSIX package: https://github.com/marketplace/actions/upload-artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@master
      with:
        name: MSIX Package
        path: MyWpfApp.Package\AppPackages\